#!/usr/bin/python3
def raise_exception():
    print("Stephen" + 1)